### ISSUE TITLE
ERRO 404

### ISSUE THREAD

**Issue by twomidia** [jaimeneto85/sitemap-xml-generator#2]
Jaime no Magento 1.9 esta ocorrendo erro 404 ao acessar a pagina TEM ALGUMA INCOMPATIBILIDADE COM ESTA VERSÃO

**Comment by JonatanM** [comment]
Também tenho esse problema.

**Comment by JonatanM** [comment]
Fiz o teste novamente mesmo erro 404 quando eu vou em  catalogo>Itaro Sitemaps ele redireciona para erro 404 do frontend

**Comment by olvleo-pr7** [comment]
Bom dia, comigo também aconteceu o mesmo problema. Minha versão é a 1.9.

**Comment by carlosmarchi** [comment]
Aqui também não consegui fazer funcionar, erro 404 redirecionando para o Frontend. Copiei os arquivos, apaguei o Cache saí do Admin, entrei novamente, apaguei todos os Caches, apaguei Sessões, saí, entrei novamente e o erro persiste. =/

**Comment by jaimeneto85** [comment]
Desculpem a demora, mas estava com outros projetos. Está corrigido 100% e testado.

Testei na 1.7.2, 1.8.1, 1.9.0 e 1.9.1

**Comment by JonatanM** [comment]
Muito obrigado @jaimeneto85 vou testar aqui
Abraços
